# Site settings
title: Amirhosien Arab
description: anjell theme 1
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Amirhosien Arab
user_description: I'm a data scientist from Iran, Graduated from Semnan University's Bachelor of Statistics course,Data analysis with Python and R programming languages and Minitab and SPSS software.
user_title: Data Analyst
email: amirxamarin@outlook.com


linkedin_username: Amirhosien
github_username:  anjell1
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

